security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
    encoders:
        App\Entity\User:
            algorithm: 'bcrypt'
    firewalls:
        register:
            pattern: /v1/user$
            stateless: true
            anonymous: true
        login:
            pattern: /v1/user/login$
            stateless: true
            anonymous: true
        main:
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - App\Security\Authenticator
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
