version: '3'

networks:
  simpleplay-network:

services:
  www:
    container_name: simplepay-www
    build: ./.docker/nginx
    ports:
      - 81:81
      - 82:80
    volumes:
      - .:/simplepay
    links:
      - app
    networks:
      simpleplay-network:
        aliases:
          - simplepay.com

  app:
    container_name: simplepay-app
    build: ./.docker/php
    volumes:
      - .:/simplepay
    links:
      - db
    networks:
      - simpleplay-network
    hostname: app

  db:
    container_name: simplepay-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: simplepay
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: simplepay
    volumes:
      - .:/simplepay
    networks:
      - simpleplay-network

  phpmyadmin:
    container_name: simplepay-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - simpleplay-network
    links:
      - db
    ports:
      - 83:80
    environment:
      MYSQL_USER: simplepay
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}